### ISSUE TITLE
Missing a support for multibyte padding.

### ISSUE THREAD

**Issue by rquadling** [carloscarucce/mb-str-pad#1]
Take a look at : https://gist.github.com/rquadling/c9ff12755fc412a6f0d38f6ac0d24fb1

**Comment by carloscarucce** [comment]
Thanks for your report. I will fix/test it ASAP

**Comment by rquadling** [comment]
I suppose I should really create a repo and package for it. Work my way through ALL the missing functions. Package them up for Packagist. But ... sometimes ... a function you find on the internet is just a function.

**Comment by carloscarucce** [comment]
That is a really good idea. But by doing some search, I've found some like these: 

https://github.com/gugglegum/mb-str-pad
https://github.com/martinlindhe/php-mb-helpers

**Comment by rquadling** [comment]
If you want to use a class, then that's going to be a pain for when/if this function becomes a standard one in PHP. Also no tests.

https://github.com/martinlindhe/php-mb-helpers suffers from the same issue you have here. No support for multi-byte padding. Poor tests (no "range" testing of values for length, no multi-byte padding).

I'll stick with my variant. Fully tested and used in production for our clients.
